command: ["streamlit", "run", "app.py"]

env:
  - name: DATABRICKS_HOST
    valueFrom: secret

  - name: DATABRICKS_TOKEN
    valueFrom: secret

  - name: LLM_EP
    value: "databricks-meta-llama-3-3-70b-instruct"

  - name: VS_ENDPOINT
    value: "my-vector-search"

  - name: VS_INDEX
    value: "ai-agent-workshop.data.financas_semantica_index"

  - name: EXPERIMENT_ID
    value: "123456789012345"

  - name: MLFLOW_TRACKING_URI
    value: "databricks"

  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"
