command: [
  "streamlit", "run",
  "app.py"
]

env:
  - name: VS_ENDPOINT
    valueFrom: "vs-endpoint"

  - name: INDEX_NAME
    valueFrom: "index-name"

  - name: LLM_ENDPOINT
    valueFrom: "llm-endpoint"

  - name: MODEL_NAME
    valueFrom: "model-name"

  - name: EXPERIMENT_ID
    valueFrom: "experiment-id"

  - name: MLFLOW_TRACKING_URI
    valueFrom: "mlflow-tracking-uri"

  - name: DATABRICKS_HOST
    valueFrom: "databricks-host"

  - name: DATABRICKS_TOKEN
    valueFrom: "databricks-token"

  - name: DATABRICKS_ACCOUNT_ID
    valueFrom: "databricks-account-id"

  - name: BASE_URL
    valueFrom: "base-url"

  - name: OPENAI_API_KEY
    valueFrom: "openai-api-key"
